Add index.html, style.css and linters
SamuelTakyiBoateng/Portfolio-RWD-desk_mob pull request #1
Opened 2023-04-07 21:28 UTC by SamuelTakyiBoateng

Add index.html with changes that allow for responsive web design for desktop & mobile

Style.css added to have a Responsive Web Design

Linters added to check for errors and avoid bugs

2023-04-07 22:34 UTC, anagudelogu requested changes
# STATUS:  CHANGES REQUIRED  ♻️ 🚧 

Hi @SamuelTakyiBoateng, 
I'm Andres.


While you have done a great job working on this milestone 💻 , there are some issues that you still need to work on to go to the next project. ♻️ 

You are almost there, keep up the good work! 🚀 

<img src="https://media2.giphy.com/media/3ohhwi25ISXC7Z4tMs/giphy-downsized-medium.gif"/>

## Highlights
✅ Great use of GitHub flow. 💯 
✅ Your project is documented professionally. 📜 
✅ Great UI design. 💻 
✅ Descriptive PR title, summary and commit messages. 💬 

## Required Changes ♻️
_Check the comments under the review._

## Optional suggestions
_Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you take them into account as they can make your code better._

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2023-04-07 22:34 UTC, anagudelogu commented on index.html
> +		</header>
- [ ] You did a great job working on this milestone! 🚀 However, please make sure to use the correct spacing between elements to follow the given design as closely as possible, currently, your navbar goes all the way to both edges, which is not what the design suggests. 🤓 🔧 

- [ ] Also, the height of your `Headline` section is very short compared to what the design suggests, please consider fixing it! 🤓 🔧 

|Template|Your design|
|---|---|
| ![image](https://user-images.githubusercontent.com/77069011/230685765-6776871c-467d-49ec-92cd-a431e0dc7e63.png) | ![image](https://user-images.githubusercontent.com/77069011/230685714-360da7d1-b49e-4b8a-a661-e63da478ca8b.png) |

2023-04-07 22:34 UTC, anagudelogu commented on index.html
> +					</div>
- [ ] Here, the button doesn't match the design, please consider using the correct colors and interaction effects (hover, focus, etc) 🤓 🔧 

|Template|Your design|
|---|---|
| ![image](https://user-images.githubusercontent.com/77069011/230686169-c1a9946a-75d7-4e0a-80f7-baaac9a5dfd6.png) | ![image](https://user-images.githubusercontent.com/77069011/230686147-875da92c-c9f7-4552-9984-e40c0ac13834.png) |

2023-04-07 22:34 UTC, anagudelogu commented on index.html
> +					</div>
- [ ] Here, please consider styling the card as is shown in the Figma design, the content should be aligned to the bottom but currently you have it centered, please fix it! 🤓 🔧 

|Template|Your design|
|---|---|
| ![image](https://user-images.githubusercontent.com/77069011/230686348-cc878450-9ece-4330-b404-b3cf7955c38e.png) | ![image](https://user-images.githubusercontent.com/77069011/230686313-3d579e92-79cc-4843-ae10-20cfa8c57a5c.png) |

2023-04-07 22:34 UTC, anagudelogu commented on index.html
> +					<div class="frameworks">
- [ ] Something similar happens here, the text should be aligned to the left, but you have it centered, please consider changing this! 🤓 🔧 

|Template|Your design|
|---|---|
| ![image](https://user-images.githubusercontent.com/77069011/230686497-a8f30f1c-3bad-464e-8731-0347ccb85fc3.png) | ![image](https://user-images.githubusercontent.com/77069011/230686464-dcaa397c-8bbd-4639-b924-6403bd3b24ec.png) |

2023-04-07 22:34 UTC, anagudelogu commented on index.html
> +							</button>
- [ ] Please make sure you use the right button colors and interactions given in the Figma design, this button doesn't match. Please fix it! 🤓 🔧 

|Template|Your design|
|---|---|
| ![image](https://user-images.githubusercontent.com/77069011/230686730-816c806a-7605-4ab6-9f05-2ffe1adba841.png) | ![image](https://user-images.githubusercontent.com/77069011/230686707-71014603-daa4-44db-821b-578b0234af4f.png) |

2023-04-07 22:34 UTC, anagudelogu commented on index.html
> +						</div>
- [ ] Please take in mind what the requirements said about designs with two inputs in the desktop version but one in mobile:

![image](https://user-images.githubusercontent.com/77069011/230686811-f966965d-1b40-452a-8c3d-fb0b6173c3ff.png)

Kindly consider removing both inputs and just keep the `full_name` one, this will come in handy for future milestones! 🤓 🔧

2023-04-07 22:34 UTC, anagudelogu commented on style.css
> +}
- [ ] I noticed that you have multiple repeated CSS properties across your stylesheet. It would be great if you can find a way of reducing this duplication of code ♻️. Remember that not repeating pieces of code will keep your codebase clean and readable. 🤓 🛠️

From [HTML & CSS best practices](https://github.com/microverseinc/curriculum-html-css/blob/main/articles/html_css_best_practices.md):
![image](https://user-images.githubusercontent.com/77069011/200000947-9e58c4d8-fed4-45f8-a822-7828c6e713f7.png)

In this case, you could do this with flex:

```CSS
.flex {
  display: flex;
}
```

And then, use it in your HTML elements where you need a flex container:

```HTML
<div class="flex"> This is a flex container </div>
```

Please, consider fixing this! 🤓

2023-04-08 13:50 UTC, SamuelTakyiBoateng commented on index.html
> +		</header>
I must appreciate the review for such details and comment. The suggested navbar and headline have been made accordingly. Thank you!

2023-04-08 13:53 UTC, SamuelTakyiBoateng commented on index.html
> +					</div>
Please, the colors and interaction effects have been changed according, and thankful for the reviewer's comment and input.

2023-04-08 13:54 UTC, SamuelTakyiBoateng commented on index.html
> +					<div class="frameworks">
My apologies for this miss. Please, the text has been aligned to the left. Thanks!

2023-04-08 13:56 UTC, SamuelTakyiBoateng commented on index.html
> +						</div>
Thank you for reverting me to this instruction. Please, the changes have been made. Thank you!

2023-04-08 14:00 UTC, SamuelTakyiBoateng commented on index.html
> +					</div>
Thank you this is correct. Please, relentless efforts have been made to adjust the styling cards. It's better than before and would a prime focus in the coming week 🙏 if possible.

2023-04-08 14:09 UTC, SamuelTakyiBoateng commented on style.css
> +}
I am very grateful for the reviewer's desire to bring out the very best in me👌. Efforts have been made to refractor the codes in order to minimize so repeats as seen in style.css line 235-265, and I'm very sure not all were done since much of my effort is been consumed by in learning the content, making it work and then refractor it as much as possible. I hope to improve on that aspect of coding with time. My apologies if some code refractoring still remains.

2023-04-08 14:11 UTC, SamuelTakyiBoateng commented on index.html
> +							</button>
Each comment made is very insightful and honest. I want to thank the reviewer and also mention that changes have been made. 🙏

2023-04-08 14:25 UTC, algerina commented on index.html
> +					</div>
- [ Optional]Nice job implementing most of the requirements however on hover the button text disappears since it has the same color as the button. Kindly consider changing the text color.

2023-04-08 14:25 UTC, algerina approved these changes
Hi  @SamuelTakyiBoateng ,

Great job so far! 

May I highlight the following: 
- [x] Your project looks awesomel✔️ 
- [x] Well done implementing all the requirements✔️ 

## STATUS: APPROVED :muscle::clap:

Congratulations! :tada:

Your project is complete!  It's time to merge it :shipit:

<img src="https://media4.giphy.com/media/l7fdqmHQ1jCg2HzQlx/giphy.gif"/>

 
 ## Optional suggestions

 - Please check the comment under the review.

_Every comment with the [OPTIONAL] prefix won't stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better. Some of them were simply missed by the previous reviewer and addressing them will really improve your application._
Cheers and Happy coding! :clap: :clap: :clap:

Feel free to leave any questions or comments in the PR thread and tag me @algerina if something is not 100% clear.

#### _**Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise.**_
------------------------------------------------------------------------------------------------------------------------------
As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using this [form.](https://airtable.com/shrQAqnBwek5a0O0s)
___
_If anything seems to be unclear to you, reach out and ask anything by commenting on this Pull Request and mention me as [Algerina](https://github.com/algerina), I will receive a notification and will respond._

[GitHub](https://github.com/algerina) | [LinkedIn](https://linkedin.com/in/amel-khiri) | [Twitter](https://twitter.com/AmelQahwadji)

_Reviewed by [Amel Khiri ](https://github.com/algerina)_

2023-04-08 15:30 UTC, merged